export const GET_POSTERS_REQUEST = 'GET_POSTERS_REQUEST';
export const GET_POSTERS_SUCCESS = 'GET_POSTERS_SUCCESS';
export const GET_POSTERS_FAILURE = 'GET_POSTERS_FAILURE';

export const ADD_POSTERS_REQUEST = 'ADD_POSTERS_REQUEST';
export const ADD_POSTERS_SUCCESS = 'ADD_POSTERS_SUCCESS';
export const ADD_POSTERS_FAILURE = 'ADD_POSTERS_FAILURE';

export const DELETE_POSTERS_REQUEST = 'DELETE_POSTERS_REQUEST';
export const DELETE_POSTERS_SUCCESS = 'DELETE_POSTERS_SUCCESS';
export const DELETE_POSTERS_FAILURE = 'DELETE_POSTERS_FAILURE';
