export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE'

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

export const USER_EDIT_REQUEST = 'USER_EDIT_REQUEST';
export const USER_EDIT_SUCCESS = 'USER_EDIT_SUCCESS';
export const USER_EDIT_FAILURE = 'USER_EDIT_FAILURE';

export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAIL = 'USER_LOGOUT_FAIL';

export const USER_FORGOT_PASSWORD_OTP_SEND_REQUEST = "USER_FORGOT_PASSWORD_OTP_SEND_REQUEST";
export const USER_FORGOT_PASSWORD_OTP_SEND_SUCCESS = "USER_FORGOT_PASSWORD_OTP_SEND_SUCCESS";
export const USER_FORGOT_PASSWORD_OTP_SEND_FAIL = "USER_FORGOT_PASSWORD_OTP_SEND_FAIL";

export const USER_FORGOT_PASSWORD_OTP_VERIFY_REQUEST = "USER_FORGOT_PASSWORD_OTP_VERIFY_REQUEST";
export const USER_FORGOT_PASSWORD_OTP_VERIFY_SUCCESS = "USER_FORGOT_PASSWORD_OTP_VERIFY_SUCCESS";
export const USER_FORGOT_PASSWORD_OTP_VERIFY_FAIL = "USER_FORGOT_PASSWORD_OTP_VERIFY_FAIL";

export const USER_SET_NEW_PASSWORD_REQUEST = "USER_SET_NEW_PASSWORD_REQUEST";
export const USER_SET_NEW_PASSWORD_SUCCESS = "USER_SET_NEW_PASSWORD_SUCCESS";
export const USER_SET_NEW_PASSWORD_FAIL = "USER_SET_NEW_PASSWORD_FAIL";

export const CLEAR_ERRORS = 'CLEAR_ERRORS';