// servicesData.js
export const contractorServices = [
    { id: 1, label: "Plumber" },
    { id: 2, label: "Electrician" },
    { id: 3, label: "Carpenter" },
    { id: 4, label: "Shuttering" },
    { id: 5, label: "Waterproofing" },
    { id: 6, label: "Heat insulation" },
    { id: 7, label: "Painter" },
    { id: 8, label: "Flooring" },
    { id: 9, label: "Pop" },
    { id: 10, label: "False Ceiling" },
    { id: 11, label: "Upvc fitting" },
    { id: 12, label: "Aluminium fittings" },
    { id: 13, label: "Glass" },
    { id: 14, label: "Fire system" },
    { id: 15, label: "Landscapers" },
    { id: 16, label: "Architects" },
    { id: 17, label: "Interior designers" },
    { id: 18, label: "Jcb movers" },
    { id: 19, label: "Construction/civil contractor" },
  ];
  
  export const supplierServices = [
    { id: 1, label: "Sanitary/bath fittings" },
    { id: 2, label: "Electrical/lightings" },
    { id: 3, label: "Tiles/flooring" },
    { id: 4, label: "Wood work" },
    { id: 5, label: "Paints and surface care" },
    { id: 6, label: "Wallpaper/pvc/vineer" },
    { id: 7, label: "Bricks/sand" },
    { id: 8, label: "Cement" },
    { id: 9, label: "Iron" },
    { id: 10, label: "Crushed stone/bajri" },
    { id: 11, label: "Modular kitchen" },
    { id: 12, label: "Hardware and tools" },
    { id: 13, label: "Marbles and stone" },
    { id: 14, label: "Gates/grills/railings" },
    { id: 15, label: "Water tanks" },
    { id: 16, label: "Solar panels" },
    { id: 17, label: "Air conditioning" },
    { id: 18, label: "Elevator" },
    { id: 19, label: "CCTV/security system" },
    { id: 20, label: "Water purifier" },
  ];
  