export const SUPPLIER_REGISTER_REQUEST = 'SUPPLIER_REGISTER_REQUEST'
export const SUPPLIER_REGISTER_SUCCESS = 'SUPPLIER_REGISTER_SUCCESS'
export const SUPPLIER_REGISTER_FAILURE = 'SUPPLIER_REGISTER_FAILURE'

export const SUPPLIER_LOGIN_REQUEST = 'SUPPLIER_LOGIN_REQUEST';
export const SUPPLIER_LOGIN_SUCCESS = 'SUPPLIER_LOGIN_SUCCESS';
export const SUPPLIER_LOGIN_FAILURE = 'SUPPLIER_LOGIN_FAILURE';

export const GET_SUPPLIER_REQUEST = 'GET_SUPPLIER_REQUEST';
export const GET_SUPPLIER_SUCCESS = 'GET_SUPPLIER_SUCCESS';
export const GET_SUPPLIER_FAILURE = 'GET_SUPPLIER_FAILURE';

export const SUPPLIER_EDIT_REQUEST = 'SUPPLIER_EDIT_REQUEST';
export const SUPPLIER_EDIT_SUCCESS = 'SUPPLIER_EDIT_SUCCESS';
export const SUPPLIER_EDIT_FAILURE = 'SUPPLIER_EDIT_FAILURE';

export const SUPPLIER_LOGOUT_REQUEST = 'SUPPLIER_LOGOUT_REQUEST';
export const SUPPLIER_LOGOUT_SUCCESS = 'SUPPLIER_LOGOUT_SUCCESS';
export const SUPPLIER_LOGOUT_FAIL = 'SUPPLIER_LOGOUT_FAIL';

export const SUPPLIER_FORGOT_PASSWORD_OTP_SEND_REQUEST = "SUPPLIER_FORGOT_PASSWORD_OTP_SEND_REQUEST";
export const SUPPLIER_FORGOT_PASSWORD_OTP_SEND_SUCCESS = "SUPPLIER_FORGOT_PASSWORD_OTP_SEND_SUCCESS";
export const SUPPLIER_FORGOT_PASSWORD_OTP_SEND_FAIL = "SUPPLIER_FORGOT_PASSWORD_OTP_SEND_FAIL";

export const SUPPLIER_FORGOT_PASSWORD_OTP_VERIFY_REQUEST = "SUPPLIER_FORGOT_PASSWORD_OTP_VERIFY_REQUEST";
export const SUPPLIER_FORGOT_PASSWORD_OTP_VERIFY_SUCCESS = "SUPPLIER_FORGOT_PASSWORD_OTP_VERIFY_SUCCESS";
export const SUPPLIER_FORGOT_PASSWORD_OTP_VERIFY_FAIL = "SUPPLIER_FORGOT_PASSWORD_OTP_VERIFY_FAIL";

export const SUPPLIER_SET_NEW_PASSWORD_REQUEST = "SUPPLIER_SET_NEW_PASSWORD_REQUEST";
export const SUPPLIER_SET_NEW_PASSWORD_SUCCESS = "SUPPLIER_SET_NEW_PASSWORD_SUCCESS";
export const SUPPLIER_SET_NEW_PASSWORD_FAIL = "SUPPLIER_SET_NEW_PASSWORD_FAIL";

export const CLEAR_ERRORS = 'CLEAR_ERRORS';